const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
test('Vercel only publishes new game',()=>{const c=JSON.parse(read('vercel.json'));assert.equal(c.outputDirectory,'public');assert.equal(c.buildCommand,'');assert.equal(c.framework,null);assert.match(read('public/index.html'),/Rumput Lebat — Game Bola 3D/);assert.ok(!fs.existsSync(path.join(root,'public/car.glb')));});
test('local script dependencies and Three r160 are available',()=>{const html=read('public/index.html');for(const [,src] of html.matchAll(/src="\.\/([^"]+)"/g))assert.ok(fs.existsSync(path.join(root,'public',src)));assert.match(read('public/game.js'),/from '\.\/three.module.js'/);assert.match(read('public/three.module.js'),/REVISION = '160'/);assert.ok(fs.existsSync(path.join(root,'public/licenses/three-LICENSE.txt')));});
test('quality presets and controls retained',()=>{const html=read('public/index.html'),js=read('public/game.js');for(const n of [60000,110000,180000])assert.ok(html.includes(`data-n="${n}"`));for(const key of ['KeyW','ArrowUp','Space','pointercancel'])assert.ok(js.includes(key));});
test('old offline worker is retired',()=>{const sw=read('public/sw.js');assert.match(sw,/skipWaiting/);assert.match(sw,/registration.unregister/);assert.match(sw,/client.navigate/);assert.ok(!sw.includes("addEventListener('fetch'"));});
